### PR TITLE
added the remember flag

### PR DESCRIPTION
**Pull request by Atoo35**
added the remember flag, it sets the yamlPath accordingly and fetches the path at first and then proceeds with the current logic.

On a side note, the .scaffolder folder wasn't created automatically for my machine. Is this a bug or an expected behaviour?

### CODE REVIEW

**Comment by cemister** [comment]
I was in a hurry and I forgot to add code to autocreate the folder. I will add it once i come back home

**Comment by cemister** [comment]
Regarding your PR: Using a database can be handy, however, I think you may be overengineering it. I think we can simply create a txt file configDir that has the path and then read it accordingly using os.ReadFile (if i recall the function for this correctly)

**Comment by Atoo35** [comment]
right i understand your point, although i am using bolt db which essentially is a file and a very light library which is made for quick read-writes and cannot store complex structures anyway. If you still think a simple txtfile should be implemented then sure i can do that

**Comment by cemister** [comment]
Yeah, but still, it would be more clear and simpler to do it using basic I/O functions. Later this can be adjusted to a config file for the tool itself, although I doubt the tool will have that much features that a whole config file would be required.

**Comment by Atoo35** [comment]
@cemister done, shifted to simple txt file

**Comment by cemister** [comment]
I have reviewed it and I'd say this is it.

Could you provide some examples of usage? So I can be sure there won't be any unexpected behaviours.

After this, I will accept your PR.

**Comment by Atoo35** [comment]
umm, just add the `--remember true` in the command and that's it, other parts of the code are untouched. Updated the readme, not sure if I updated it correctly

**Comment by cemister** [comment]
- `--remember` - new flag introduced to save the default path to access the yaml files.

->

- `--remember` - new flag introduced to save the custom path to config folder with yaml files, specified in `--configDir` flag, avoiding the need to specify the path each time. To reset, set `--configDir` to `""`. The custom path is saved to a text file, which is located in same directory as scaffolder executable, meaning you can edit the path without running the tool itself.

**Comment by Atoo35** [comment]
done, thanks a lot for being so kind and patient

**Comment by cemister** [comment]
It's pleasure to work with you.

Last 2 things;

Check the third part of Todo

- [ ] Remember custom config directory if specified AND `--remember` is true (by default false)

->

- [x] Remember custom config directory if specified AND `--remember` is true (by default false)

Remove the executables inside repo (scaffolder_*). Speaking about executables, could you please build executables for each OS (Windows, Linux, MacOS) and create a release? Because as I said I don't have access to a computer right now.

Set GOARCH to amd64 by running GOARCH=amd64 in the terminal and then build it for each os:

```
GOOS=windows
go build -o scaffolder_win.exe
GOOS=linux
go build -o scaffolder_linux
GOOS=darwin
go build -o scaffolder_macos
```

**Comment by Atoo35** [comment]
updated the readme, i am excited to create the release and execs, never done it before so lemme figure it out. anyway I need to do that after you merge so its fine

**Comment by cemister** [comment]
Merging.

**Comment by cemister** [comment]
I've added you to collaborators, head over main page of the repo and there should be releases tab somewhere. Go there and click Draft new release

**Comment by Atoo35** [comment]
on it

**Comment by Atoo35** [comment]
@cemister created a draft release, could you give it a look and tell me what I need to change?

**Comment by Atoo35** [comment]
also can we add the "Contributors" tab on the right panel 🤓

**Comment by cemister** [comment]
@Atoo35 So I looked at main.go again and noticed you used Fatal function in the wrong way. I fixed it for better error handling. I might be asking for too much, but can you remove and recreate the release? Build the project as above again and create the release.

**Comment by Atoo35** [comment]
ahh i see lemme see what i did wrong

**Comment by Atoo35** [comment]
ahh that is a beautiful code you wrote there. love it

**Comment by Atoo35** [comment]
theres a typo in the main file in the very first line near `package main`. Should I fix it by creating a new branch or directly to master?

**Comment by Atoo35** [comment]
updated the binaries with fixing the main.go file locally

**Comment by cemister** [comment]
Directly to master @Atoo35

**Comment by Atoo35** [comment]
done

**Comment by cemister** [comment]
Alright! Now a release can be created.

**Comment by Atoo35** [comment]
i have created a draft release, is that good to be published?

**Comment by cemister** [comment]
@Atoo35 Were the binaries created after fixing the issues above? If so, yes

**Comment by Atoo35** [comment]
yes the binaries were created after fixing all issues. LETSS GOOO!!!

**Comment by cemister** [comment]
Very much thank you for contributing to my project!

**Comment by Atoo35** [comment]
No problem at all, love working with you. This first contribution to open source turned out to be fantastic. Do let me know what more you have in mind to build.

Also can you add the "Collaborators" tab on the right pane please? Just too excited about this hahaha

**Comment by cemister** [comment]
Sorry, how do I do that? Can't find anything in settings.

**Comment by Atoo35** [comment]
apparently it took some time to be visible, its a default behavior, I can see contributors tab in the repo now. :)

**Pull request merged**
