### PR TITLE
added cobra-cli to make it robust and extendible

### PR DESCRIPTION
**Pull request by Atoo35**
Hey @cemister, this is a wonderful project and I like the idea of it. 
I recently started learning GO from various sources, one of which is Jon Calhoun. From one of his exercises I came across cobra-cli and I have added the same in this PR.
I am a newbie in GO and this is my first open source contribution so please bear that in mind while reviewing the PR.
I would love to connect with you and discuss if we can merge this and if not then what changes would be good to be made

Looking forward to hearing from you

### CODE REVIEW

**Comment by Atoo35** [comment]
oh i forgot to mention how to work with this.
just use the `go install` command to install it as the name of the folder and then use `scaffolder` in the terminal to see the output. cobra takes care of --help command and even help for the create command.
scaffolder create <your flags here> should work just fine.

if the install method doesn't work check the PATH folder or else go build and use the build file to run the commands

**Comment by cemister** [comment]
That would indeed make the project easier to extend. However, as of now I do not know what else I could add. It currently serves only one function to scaffold projects, and flag library does it well. In future though, when there'll be ideas of features to add, I will consider this. I won't close your PR because of reasons above. So in short I don't disagree with your reasoning, but I think it's better to be done later.

**Comment by cemister** [comment]
@Atoo35 About the go install: i think the current instructions are better because if someone simply wants to use the product they wouldn't download go, then the source code and then `go install` in the source code's directory

**Comment by Atoo35** [comment]
Thanks a ton for responding to my request. I understand the points you raised. The simplest extension could be allowing the user to set up the scaffolders config folder to someplace else or something like that. I understand and happy to wait.
About go install I just pointed that out for you to test it out on your machine not for the user to install go. Sorry for the misunderstanding

**Comment by cemister** [comment]
@Atoo35 In upcoming 1.1.5 there will be an extra flag for specifying the path to your custom config folder with the ability to remember the path thus avoiding the need to specify it every time

**Comment by Atoo35** [comment]
Ahh wonderful

**Comment by Atoo35** [comment]
@cemister do let me know if there is some other way I can contribute 😁

**Comment by cemister** [comment]
@Atoo35 I have just added a TODO section to README. So if you want, you can contribute

**Comment by cemister** [comment]
Now that Scaffolder was updated several times, this PR has conflicts with master branch. Closing it. Later on a similiar PR can be done, just using latest version this time.

**Comment by Atoo35** [comment]
Alrighty np

**Pull request closed without merging**
