### PR TITLE
Yaml variables

### PR DESCRIPTION
**Pull request by Gwali-1**
variables can now be set using a --variable flag to be used in the scaffold file
flag takes values in the format --variables key1:value1, key2:value
these are parsed and available to be used in the content of a file when scaffolding with synthanx {key}!

let me know if there is something i nee to change perharps

### CODE REVIEW

**Comment by cemister** [comment]
Only few things:
1) Update README to contain more detailed information on how to use variables
2) move yamlVariables in helper folder

**Comment by Gwali-1** [comment]
where do i add info about new flag in readme? i assume youre going to release new binaries ?

**Comment by cemister** [comment]
@Gwali-1 in Usage section. You may as well add examples to existing ones

Yup.

**Comment by Gwali-1** [comment]
so is should i add the flag under a new version release  heading ? like Scaffolder 1.1.7?
Alright  will add an example

**Comment by cemister** [comment]
Yes

**Comment by cemister** [comment]
@Gwali-1 In yamlVariable valu should be value, it seems you've misspelled it

**Comment by Gwali-1** [comment]
fixed that too

**Comment by cemister** [comment]
Merged! Thank you!

**Comment by cemister** [comment]
@Atoo35 Please create new release for 1.1.7 with new features. Make sure you're creating releases for main repo rather than your own.

**Comment by Atoo35** [comment]
on it sire!!

**Comment by Gwali-1** [comment]
@cemister happy to help!

**Comment by Atoo35** [comment]
@cemister release created!!

**Pull request merged**
